# Preface {.unnumbered}

This will be an online book about causal inference.

Here are some other resources for learning causal inference:

## UC Davis courses

- [EPI 205](https://catalog.ucdavis.edu/search/?q=EPI+205) "Principles of Epidemiology"

- [EPI 206](https://catalog.ucdavis.edu/search/?q=EPI+206) "Epidemiologic Study Design"

- [EPI/SPH 207](https://catalog.ucdavis.edu/search/?q=EPI+207) "Advanced Epidemiologic Methodology"

- [EPI 225](https://catalog.ucdavis.edu/search/?q=EPI+225) "Advanced Topics in Epidemiology Methods"

- [POL 285](https://catalog.ucdavis.edu/search/?q=POL+285) "Statistics of Causal Inference in Political Science"
- [MGB/MGP/MGT 454A](https://catalog.ucdavis.edu/search/?q=MGB+454A) "Causal Inference and Statistical Experiments"
  - syllabus: <https://webapps.aws.ucdavis.edu/public/documents/4861649/Syllabus>https://schedule.aws.ucdavis.edu/public/documents/5319910/Syllabus
- [PSC 204B](https://catalog.ucdavis.edu/search/?q=PSC+204B) "Causal Modeling of Correlational Data"
- [PSC 205C](https://catalog.ucdavis.edu/search/?q=PSC+205C) "Structural Equation Modeling"

Course search options:

- <https://schedule.aws.ucdavis.edu/courseScheduling>
- <https://catalog.ucdavis.edu/course-search/>
- <https://catalog.ucdavis.edu/courses-subject-code/>


## Online Videos

- ["Introduction to Causal Inference"]( <https://ucdhs.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=43e9eb6f-3ed9-41ac-8ad9-ae22016572c8%20>) (slides [here](https://health.ucdavis.edu/media-resources/ctsc/documents/pdfs/causal-inference-intro-2022.pdf))

- [Online Causal Inference Seminar series](https://www.youtube.com/channel/UCiiOj5GSES6uw21kfXnxj3A/videos)


## UC Davis Datalab learning group

- <https://datalab.ucdavis.edu/causal-inference/>
   - [Reading list](https://docs.google.com/document/d/1K0QZFSjQIYnOTahpRK7Q83eaiIIFjfa-clSbj_ifgco/edit?tab=t.0#heading=h.farbmh6n76gq)

Other links:

- <https://cameron.econ.ucdavis.edu/causal/>

- <https://datalab-icmat.github.io/causal_reading_group.html>

- Lab exercises by [Ben Noble](https://benjaminnoble.org/): <https://github.com/bennoble/causal-inference-2022>

## Books

- @pearlprimer

- @hernan2020causal
